detectors:
  DuplicateMethodCall:
    exclude:
      - "Array#pluck"
      - "Pathname#change_dir"
      - "singleton_class#make_temp_dir"
  FeatureEnvy:
    exclude:
      - "Array#compress"
      - "Hash#compress"
      - "Hash#fetch_deep"
      - "String#squish"
  ManualDispatch:
    exclude:
      - "Array#compress"
      - "Hash#compress"
      - "Object#to_proc"
  NestedIterators:
    exclude:
      - "Array#pluck"
  TooManyStatements:
    exclude:
      - "Array#pluck"
      - "Hash#flatten_keys"
      - "String#trim_middle"
  UncommunicativeMethodName:
    exclude:
      - "Kernel#Pathname"
      - "Time#rfc_3339"
