detectors:
  ControlParameter:
    exclude:
      - "String#pluralize"
      - "String#singularize"
  DuplicateMethodCall:
    exclude:
      - "Pathname#change_dir"
      - "singleton_class#make_temp_dir"
  FeatureEnvy:
    exclude:
      - "Array#compress"
      - "Hash#compress"
  LongParameterList:
    enabled: false
  ManualDispatch:
    exclude:
      - "Array#compress"
      - "Hash#compress"
  TooManyStatements:
    exclude:
      - "Hash#flatten_keys"
  UncommunicativeMethodName:
    exclude:
      - "Kernel#Pathname"
