detectors:
  FeatureEnvy:
    exclude:
      - "Hash#compress!"
  IrresponsibleModule:
    enabled: false
  ManualDispatch:
    exclude:
      - "Hash#compress!"
  UncommunicativeMethodName:
    exclude:
      - "Refinements::Pathnames#Pathname"
