detectors:
  ControlParameter:
    exclude:
      - "String#pluralize"
      - "String#singularize"
  DuplicateMethodCall:
    exclude:
      - "Pathname#change_dir"
  FeatureEnvy:
    exclude:
      - "Array#compress!"
      - "Hash#compress!"
  ManualDispatch:
    exclude:
      - "Array#compress!"
      - "Hash#compress!"
  UncommunicativeMethodName:
    exclude:
      - "Kernel#Pathname"
